opt_in_rules: # some rules are only opt-in
  - empty_count
  - redundant_nil_coalescing
  - closure_spacing
  - sorted_imports
  - valid_docs
  - nslocalizedstring_require_bundle

included:
  - Sources

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests
  - Example

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
